### ISSUE TITLE
サンプルインスタンスDocinfoの項目の表記違い

### ISSUE THREAD

**Issue by Masami-OGATA** [skoba/mml#101]
Docinfoの項目で以下のような表記になっていますが

　　　1.1.2. securityLevel
　　　1.1.3. accessRight

それぞれ
　　　1.1.2. mmlSc:securityLevel
　　　1.1.3. mmlSc:accessRight
ではないでしょうか？

**Comment by skoba** [comment]
これについては、元々の仕様が上記のnamespace無しの法が正しいようです。そのように修正を加えます。

**Comment by skoba** [comment]
仕様とスキーマの違うところで、仕様通りであれば上の方が正しいのですが、スキーマとしては下が正しいようです。
