### ISSUE TITLE
ドキュメントのmmlSc:accessRightについて

### ISSUE THREAD

**Issue by stellaplacehoshi** [skoba/mml#123]
MML4.1.2の対応中に気づいたのですが、
ドキュメントのmmlSc:accessRightのpermitの説明の欄がtrue,falseになっています。
none,read,write,delete,allではないでしょうか？
※xsdはnone,read,write,delete,allになっています。

**Comment by skoba** [comment]
この部分は、MML 2.3のドキュメントから引っ張ってきてたので間違いが出ていたようです。
3.0の文書から引き直しました。
