### ISSUE TITLE
処方箋モジュール　mmlPs:duration(服薬期間（日数）)データ型記述相違

### ISSUE THREAD

**Issue by Masami-OGATA** [skoba/mml#128]
エレメント一覧表、表記例では、durationとして記述されていますが、
エレメント解説では、以下のようにdecimalとなっています。
**8.15.3.11. M24.2.6. mmlPs:duration
【内容】服薬期間（日数）
【データ型】decimal
【省略】可
【説明】総量のみが記載される外用剤などの場合には省略可**

**Comment by skoba** [comment]
スキーマでもdurationとなっており、解説の間違いですね。
