### ISSUE TITLE
Mismatch of occurrence Indicators in the Surgery

### ISSUE THREAD

**Issue by mbot-dev** [skoba/mml#70]
確認です。左が規格の解説書、右が xsd

・surgeryItemのsurgicalStaffs            minOccurs=1  vs  minOccurs=0 
・surgicalInfoのsurgicalDepartment   maxOccurs=1  vs  maxOccurs= unbounded
・surgicalInfoのpatientDepartment     maxOccurs=1  vs  maxOccurs= unbounded
・staffのstaffInfo                                  maxOccurs=1  vs  maxOccurs= unbounded

**Comment by skoba** [comment]
MML 3.0のDTDが以下のようになっていますね。これを元にすると、以下のようになっておりますので文書とXSDの両方を調整する必要がありそうです。

- surgeriItemのsurgicalStaffs minOccurs="0" maxOccurs="1"
- surgicalInfoのsurgicalDepartment minOccurs="0" maxOccurs="1"
- surgicalInfoのpatientDepartment minOccurs="0" maxOccurs="1" 
- staffのstaffInfo minOccurs="1" maxOccurs="1"
- おまけ：mmlSg:durationのデータ型をドキュメント通りxs:durationに変更


 <!ELEMENT mmlSg:SurgeryModule (mmlSg:surgeryItem+)>
 <!ELEMENT mmlSg:surgeryItem (
 mmlSg:surgicalInfo,
 mmlSg:surgicalDiagnosis,
 mmlSg:surgicalProcedure,
mmlSg:surgicalStaffs?,
mmlSg:anesthesiaProcedure?,
mmlSg:anesthesiologists?,
mmlSg:anesthesiaDuration?,
mmlSg:operativeNotes?,
mmlSg:referenceInfo?,
mmlSg:memo?)
>
<!ELEMENT mmlSg:surgicalInfo (
mmlSg:date,
mmlSg:startTime?,
mmlSg:duration?,
mmlSg:surgicalDepartment?,
mmlSg:patientDepartment?)
>
<!ATTLIST mmlSg:surgicalInfo
mmlSg:type %mmlDt.MML0021; #IMPLIED
>
<!ELEMENT mmlSg:surgicalDepartment (mmlDp:Department+)>
<!ELEMENT mmlSg:patientDepartment (mmlDp:Department+)>
<!ELEMENT mmlSg:date (#PCDATA)>
<!ELEMENT mmlSg:startTime (#PCDATA)>
<!ELEMENT mmlSg:duration (#PCDATA)>
<!ELEMENT mmlSg:surgicalDiagnosis (mmlRd:RegisteredDiagnosisModule+)>
<!ELEMENT mmlSg:title (#PCDATA)>
<!ATTLIST mmlSg:title
mmlSg:code CDATA #IMPLIED
mmlSg:system CDATA #IMPLIED
>
<!ELEMENT mmlSg:memo (#PCDATA)>
<!ELEMENT mmlSg:surgicalProcedure (mmlSg:procedureItem+)>
<!ELEMENT mmlSg:procedureItem (
(mmlSg:operation | mmlSg:operationElement),
mmlSg:procedureMemo?)
>
<!ELEMENT mmlSg:operationElement (mmlSg:operationElementItem+)>
<!ELEMENT mmlSg:operationElementItem (mmlSg:title)>
<!ELEMENT mmlSg:surgicalStaffs (mmlSg:staff+)>
<!ELEMENT mmlSg:staff (mmlSg:staffInfo)>
<!ATTLIST mmlSg:staff
mmlSg:superiority %xs.positiveInteger; #IMPLIED
mmlSg:staffClass CDATA #IMPLIED
>
<!ELEMENT mmlSg:staffInfo (mmlPsi:PersonalizedInfo+)>
<!ELEMENT mmlSg:anesthesiaProcedure (mmlSg:title+)>
<!ELEMENT mmlSg:anesthesiologists (mmlSg:staff*)>
<!ELEMENT mmlSg:operativeNotes %mmlxhtmlInline;>
<!ELEMENT mmlSg:referenceInfo (mmlCm:extRef+)>
<!ELEMENT mmlSg:operation (#PCDATA)>
<!ATTLIST mmlSg:operation
mmlSg:code CDATA #IMPLIED
mmlSg:system CDATA #IMPLIED
>
<!ELEMENT mmlSg:procedureMemo (#PCDATA)>
<!ELEMENT mmlSg:anesthesiaDuration (#PCDATA)>

**Comment by mbot-dev** [comment]
小林先生、

確認しただけです。XSD を正とし解説書の方は無視で進めています。（3.0のDTDまでは見なかった）

**Comment by skoba** [comment]
吉原先生ともお話ししたのですが、通常はDepartmentが複数記載されることはないのでDTDでの定義が複数であっても文書通り1個しか出てこないので問題が無かったのだろうということでした。ちょっとこのあたり確認してみます。

**Comment by skoba** [comment]
DTDに文書合わせる方針で行きます

**Comment by mbot-dev** [comment]
了解です。XSDが正で。
