### ISSUE TITLE
MM4.1.1仕様コメント（４）　10. MMLコンテンツ モジュール詳説

### ISSUE THREAD

**Issue by Masami-OGATA** [skoba/mml#75]
『MMLではユースケースに応じて下記のモジュールを設計した。各モジュールを1文書単位としてMmlItemに記載することとしている。...』

```
MmlItemは、contentでは？　MmlItemの説明がどこにもないので。
```

**Comment by skoba** [comment]
５．２にMmlModuleItemという記述があるので、MmlModuleItemに修正します。

**Comment by Masami-OGATA** [comment]
MmlModuleItem配下には、docInfoとcontentがあります。
content配下に各モジュールがあるということが分かりにくいと思います。

以下の部分で、その説明を修正してみました。

『
5.2. MML bodyブロック

MML bodyブロックは複数のitemブロック（MmlModuleItem)で構成されており、各itemブロックにはヘッダ情報（docInfo)とその内容を表すコンテンツモジュール**(content)**が配置される。

docInfoには、記載日、記載者、文書種別、タイトル、文書ID、親文書ID、グループID、アクセス権、外部参照リストが記載されている。

**content**には下記のモジュールのいずれか一つが格納される。

』

**Comment by skoba** [comment]
ありがとうございます。これで修正しました。
