### ISSUE TITLE
MM4.1.1仕様コメント（８）Table 27. エレメント一覧表の表記

### ISSUE THREAD

**Issue by Masami-OGATA** [skoba/mml#79]
mmlHd:HDxxxx, mmlHd:Hdxxxxx, mmlHd:HDxxxxと統一したほうがよいとおもいますが。

	M26.1.5.1.1.10.1.	mmlHd:dialysateTempValueのmmlHd:unitのOccurrenceは#REQUIREDでは？

　　M26.　**Mml**Hd:HemoDialysisModule　→　**mml**Hd:HemoDialysisModule

　　M26.1.4.2.    mmlHd:BloodAccess

		**mm**Hd:baStatus  →　 **mml**Hd:baStatus　では？

	M26.1.6.1.6.	mmlHd:weightCorrectionのTable id

		**Deault**: "kg"　　→　　**Default**: "kg"　では？

　　M26.1.7.1.3.4.　　mmlHd:extRef　→　mmlCm:extRef
　　　　　従って以下不要では?
　　　　　　　mmlHd:contentType　　string　　#IMPLIED
　　　　　　　mmlHd:medicalRole　　string　　#IMPLIED
　　　　　　　mmlHd:title　　　　　string　　#IMPLIED
　　　　　　　mmlHd:href　　　　　 string　　#IMPLIED

**Comment by skoba** [comment]
他のモジュールにあわせて、mmlHd:Hd, hD, HDなどを統一しようと最初試みたのですが、そもそも他のモジュールも統制がとれていませんでした。次のMajorリリースのときにはルール作りから始めたいと思います。

**Comment by skoba** [comment]
Mml, mml, MMLもブレがありました。
