### ISSUE TITLE
MM4.1.1仕様コメント（11）Table 24. エレメント一覧表

### ISSUE THREAD

**Issue by Masami-OGATA** [skoba/mml#82]
M23.4.10.2.　　mmlFs:bofPeriodStart　→　mmlFs:bofPeriodStartTime
　　M23.4.10.3.　　mmlFs:bofPeriodEnd　　→　mmlFs:bofPeriodEndTime　　名称変更ですか?

**Comment by skoba** [comment]
変更です。というより、XSDに併せてドキュメント修正しました。

**Comment by Masami-OGATA** [comment]
マッピング表mml4_flowsheet.xlsxの修正もお願いいたします。
